# 3 Intro to Python language

The main programming environment in this class will be [Python](https://www.python.org), and specifically the interactive [ipython](http://ipython.org) environment. The latter provides in combination with the [matplotlib](http://matplotlib.org) package and further extension packages, such as [numpy](http://www.numpy.org), [scipy](http://www.scipy.org) and [sympy](http://www.sympy.org) a very powerful environment for scientific and mathematical computing. There are many, many other extension packages.

One of many available resources is the [Python Tutorial](https://docs.python.org/3/tutorial) which provides more detail and is more comprehensive compared to our coverage here. 

### Starting a new notebook
* Start notebook (you may to select a kernel, select _Python3_), give it the name `test1.ipynb`
* Many things missing, e.g. you can't do a square `sqrt` or a sine `sin`.

In [1]:
# this is a comment
sqrt(4)

NameError: name 'sqrt' is not defined

### Loading libraries
* A key python feature: modules providing additional functionality, such as `numpy` 
* Load libraries such as numpy: `import numpy as np`

In [2]:
import numpy as np1
np1.sqrt(4)

2.0

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


#### Pylab environment
* Magic command `%pylab inline` is executed by default. It loads numpy and matlab into interactive namespace and makes sure plots are shown. 
* This is very convenient - but beware of **namespace** mingling $\rightarrow$ _discuss name spaces_.
* `%pylab` needs a _backend_, i.e. an interface that will take care of the actual plot and image generation. The default is `%pylab inline` and it creates static images that will be properly exported in html or pdf. 
* For interactive figures, try 
    - in JupyterHub `%pylab ipympl`
    - in Jupyter Notebook `pylab nbagg`

In [4]:
%pylab ipympl

ModuleNotFoundError: No module named 'ipympl'

In [5]:
sqrt(4.)

2.0

In [6]:
import mpmath as mp
mp.sqrt(4.)

mpf('2.0')

In [7]:
import scipy as sp
sp.sqrt(4.)

2.0

Note that at this point we have four different ways to do a sqrt. Among these `sqrt` and `np.sqrt` are the same. Get help from the doc strong, and the location of the routine by adding a `?` to any command or variable:

In [8]:
#sqrt?
#np.sqrt?
sp.sqrt?
#mp.sqrt?

Signature: sp.sqrt(x)
Docstring:
Compute the square root of x.

For negative input elements, a complex value is returned
(unlike `numpy.sqrt` which returns NaN).

Parameters
----------
x : array_like
   The input value(s).

Returns
-------
out : ndarray or scalar
   The square root of `x`. If `x` was a scalar, so is `out`,
   otherwise an array is returned.

See Also
--------
numpy.sqrt

Examples
--------
For real, non-negative inputs this works just like `numpy.sqrt`:

>>> np.lib.scimath.sqrt(1)
1.0
>>> np.lib.scimath.sqrt([1, 4])
array([ 1.,  2.])

But it automatically handles negative inputs:

>>> np.lib.scimath.sqrt(-1)
(0.0+1.0j)
>>> np.lib.scimath.sqrt([-1,4])
array([ 0.+1.j,  2.+0.j])
File:      c:\users\koen\anaconda3\lib\site-packages\numpy\lib\scimath.py
Type:      function


So, who cares? Well, the sqrt functions are really different. Try how they respond to a negative argument:

In [9]:
sqrt(-1)

C:\Users\koen\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [10]:
sp.sqrt(-1)

1j

In [11]:
mp.sqrt(-1)

mpc(real='0.0', imag='1.0')

In [12]:
sp.sqrt(-1)

1j

We have introduced here three important concepts:
* name spaces
* libraries
* the built-in help function, the doc strings

## Basic python language elements and tasks in python

### Variables
Variables and choosing variable names: 
- don't use possible function names or other things as variable names that could mean something, such as `and, as, assert, break, class, continue, def, del, elif, else, except, False, finally, for, from, global, if, import, in, is, lambda, None, nonlocal, not, or, pass, raise, return, True, try, with, while,` and `yield`
- use mnemonic names
- be mindful of name space, more of that later

In [13]:
ifb=3               # this is not a good name
i_frame_buffer = 3  # this is a better name, maybe a bit too long
iframbuf = 3        # compromise

### Data types
There are [numerous data types](https://en.wikibooks.org/wiki/Python_Programming/Data_Types) for different use cases. An import difference between objects is whether they are [mutable or immutable types](https://en.wikibooks.org/wiki/Python_Programming/Data_Types#Mutable_vs_Immutable_Objects). For example, arrays are mutable, their elements can be changed. (This can lead in practice to [unexpected results](https://gist.github.com/fherwig/48b3fc2a920833c6077891982ad122d7).) Tupples are immutable.

Here are some of the most important:

Immutable types | comment | example
---|---|---
integer | can be written without a fractional component | `i = 2`
floats | real numbers, come in different precision, i.e. `float64` | `x = 2.1145`, `np.pi`
complex | complex numbers, e.g. scipy.sqrt(-1) | `1j`
strings | a sequence of characters | `name='Alfred'`
tuple | immutable list of numbers | `a=(1,2,3)`

In [14]:
i=2, print(i)

NameError: name 'i' is not defined

In [15]:
first_name='Claudia'
second_name='jease'

In [16]:
first_name?

Type:        str
String form: Claudia
Length:      7
Docstring:  
str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.


Mutable types | comment | example
---|---|---
lists | a list of any combination of data types | `mylist = [1,np.pi,name,a,'Hello World!`]
arrays | a numpy construct, vectors or higher dimenstional, contains numbers | `b=np.array(a,dtype='float64')`
dictionary | elements given by key | `ages = {'Anna':25,'Frank':17,'Gandalf':107}`

In [17]:
a=12.5

In [18]:
mylist = [1,np.pi,first_name,a,'Hello World!']

In [19]:
print(mylist)

[1, 3.141592653589793, 'Claudia', 12.5, 'Hello World!']


In [20]:
abc_list = [mylist,987.]

In [21]:
abc_list[0][2], abc_list[1]

('Claudia', 987.0)

#### Scalar variables and lists

In [22]:
i = 2                   #  integer
a = 4.2                 #  float
z=3+2j; y=1-4j          #  complex
print(z*y,z-y)

(11-10j) (2+6j)


In [23]:
c = 'Frank'             # a character
a_list = [2, 'b']       # a list
a_list.append(c)        # append an element to list 
print(a_list)
a_list.append('[7,6]')  # append list item to list
print(a_list)

[2, 'b', 'Frank']
[2, 'b', 'Frank', '[7,6]']


#### Create or add to lists

In [24]:
a_list.append(5)    # append is a method associated with the list object

In [25]:
a_list

[2, 'b', 'Frank', '[7,6]', 5]

An effective way to generate a list with an integer sequence of number is with the [range](https://docs.python.org/2/library/functions.html#range) function, which is a list generator:

In [26]:
jlist = list(range(0,6))
jlist

[0, 1, 2, 3, 4, 5]

The same and more could be accomplished with an implicit or implied `for` loop, also refered to as _list comprehension_:

In [27]:
ilist = [i for i in range(0,21,3)]
ilist

[0, 3, 6, 9, 12, 15, 18]

In [28]:
for k in range(3):
    print(k)

0
1
2


In the above example, what is the role of the third argument of `range`?

#### Dictionaries

In [29]:
ages={}
ages["Paul"]=54
ages

{'Paul': 54}

In [30]:
ages = {'Anna':25,'Frank':17,'Gandalf':107}  # a dictionary
print(ages['Frank'])

17


In [31]:
print(ages.keys())

dict_keys(['Anna', 'Frank', 'Gandalf'])


In [32]:
ages.values()

dict_values([25, 17, 107])

#### Working with numbers and strings
* Convert scalars

In [33]:
i=2
print("Float: ",float(i), ", String: ",str(i))

Float:  2.0 , String:  2


In [34]:
'Frank is '+str(i)

'Frank is 2'

* Adding strings

In [35]:
import numpy as np

In [36]:
str(i)+"Hello"+str(np.pi)

'2Hello3.141592653589793'

* Slicing

In [37]:
filename='aaa-report-data.dat'
filename[2:-1]

'a-report-data.da'

* [Arithmetic operators](https://www.programiz.com/python-programming/operators#arithmetic)

In [38]:
2+2  # int and int returns int 
     # (holds for subtraction and multiplication as well)

4

In [39]:
1/3  # float division

0.3333333333333333

In [40]:
4//3 # floor division

1

In [41]:
7%5  # modulus

2

##### 

#### Algebra
We can use variables we have already assigned and create new ones.

In [42]:
g=111

In [43]:
g = 2*a + 2
print(g)

10.4


In [44]:
print(2+a/4)

3.05


In [45]:
print((2+a)/4)  #be careful where you place brackets

1.55


#### Array creation

In [46]:
# %pylab nbagg

In [47]:
%pylab ipympl

ModuleNotFoundError: No module named 'ipympl'

In [ ]:
x = linspace(0.76,10,7) # a numerical array, floats
print(x)

In [48]:
zeros(10)+1 - ones(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Example: Make list with numbers and create array from that.

#### Dictionaries

#### Boolean

In [49]:
istrue = True           # boolean

In [50]:
# check for boolean
if istrue:
    print('It is true!')

It is true!


In [51]:
# if in doubt what something is - just ask:
#x?
#or
type(istrue)

bool

In [52]:
a = 1.1
print(type(a))

<class 'float'>


In [53]:
# type of a variable
print(type(x), type(a))

NameError: name 'x' is not defined

In [54]:
# we can check for the type:
if type(a) == "float":
    print('Variable a is a float!')

In [55]:
# why did this not work? type is not of type string!
if type(a) == float:
    print('Variable a is a float!')

Variable a is a float!


#### Printing, formatting text and numbers

* slicing of arrays

In [59]:
x='11'

In [60]:
print(x[2:4])

* formatted output (we will often want the answer of a problem in a formatted output statement!)

In [61]:
print("0%10s made %d measurements, the first was %10.1E\
 and the average was a = %g" % (c,i,x[0],a))

TypeError: must be real number, not str

In [62]:
ctest="0%10s made %d measurements, the first was %10.1E\
 and the average was a = %g" % (c,i,x[0],a)

TypeError: must be real number, not str

In [63]:
ctest

NameError: name 'ctest' is not defined

Commonly used `printf` format specifications:
```
%s a string
%d an integer
%0xd an integer padded with x leading zeros
%f decimal notation with six decimals
%e compact scientific notation, e in the exponent 
%E compact scientific notation, E in the exponent 
%g compact decimal or scientific notation (with e) 
%G compact decimal or scientific notation (with E) 
%xz format z right-adjusted in a field of width x 
%-xz format z left-adjusted in a field of width x 
%.yz format z with y decimals
%x.yz format z with y decimals in a field of width x 
%% the percentage sign (%) itself
```

#### Input/output

In [45]:
# ask for user input:
user_input = input("Voltage: [V]")

Voltage: [V] 110


In [46]:
print('User voltage is %gV.' % float(user_input))

User voltage is 110V.


In [55]:
# writing a file
f = open('test.txt',mode='w')
f.write("1 2 3 \n4 5 6 \n7 8 9")
f.close()

In [57]:
!cat test.txt

1 2 3 
4 5 6 
7 8 9

In [45]:
# reading a file
g = open('test.txt','r')
for line in g:
    print(line)
g.close()

FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

In [58]:
g_array = np.loadtxt('test.txt')

In [59]:
print(g_array)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [61]:
g_array[1][2]

6.0

#### Flow control: for and while loops, if statement

In [62]:
range(5)

range(0, 5)

In [65]:
# if statement
for i in range(1,8,2):
    if i < 4:
        print(i)
print('Hello World!')

1
3
Hello World!


In [ ]:
# another if example
print(i)
if i > 1:
    print(i)

In [71]:
# while statement
i=0
while i < 4:
    print(i)
    i += 1
    

0
1
2
3


In [67]:
# for loop
things = ['abc', 'def', 'ghi']
modified_things = []
for thing in things:
    mod_thing = thing[0]
    modified_things.append(mod_thing+"_label")  

In [68]:
modified_things

['a_label', 'd_label', 'g_label']

Syntax in python: formatting matters!

In [69]:
# implied loops, list comprehension
modified_things = [thing[0]+"_label" for thing in things]

In [70]:
modified_things

['a_label', 'd_label', 'g_label']

Another example: reading data from text file and mangling data in a for loop

In [74]:
# show file
!ls data/iniab1.4E-02As09.ppn
# show content of file
!cat data/iniab1.4E-02As09.ppn

data/iniab1.4E-02As09.ppn
  1 h   1         7.1538567255E-01
  2 he  4         2.7025513111E-01
  6 c  12         2.4825306734E-03
  6 c  13         3.0083012115E-05
  7 n  14         7.3396723494E-04
  7 n  15         1.8049744286E-06 

In [46]:
# open file and attach to file object variable
f.close()
f=open('data/iniab1.4E-02As09.ppn')

AttributeError: 'builtin_function_or_method' object has no attribute 'close'

In [47]:
# what is in f
f.readlines()

AttributeError: 'builtin_function_or_method' object has no attribute 'readlines'

In [48]:
# read data and save it into variables
ind=[];elem=[];A=[];X=[]
i=0
for line in f.readlines():
    a,b,c,d=line.split()
    i += 1         # the first column in the file contains the charge 
    ind.append(i)  # number; we don't need it, but an index variable 
    elem.append(b) # would be useful
    A.append(c)
    X.append(d)

AttributeError: 'builtin_function_or_method' object has no attribute 'readlines'

In [84]:
# read ini abund tester
for i in range(len(ind)):
    print (ind[i],elem[i],A[i],X[i])

1 h 1 7.1538567255E-01
2 he 4 2.7025513111E-01
3 c 12 2.4825306734E-03
4 c 13 3.0083012115E-05
5 n 14 7.3396723494E-04
6 n 15 1.8049744286E-06


Often we have two lists and want to do something with each pair, e.g. formatted output. In this case the [zip](https://docs.python.org/3.3/library/functions.html#zip) function is useful: 

In [85]:
clist = ['a','f',"go",'tot']
alist = [3.,2.35456,7.1,6]
for c,a in zip(clist,alist):
    print("%3s = %4.2f" % (c,a))

  a = 3.00
  f = 2.35
 go = 7.10
tot = 6.00


In [87]:
for i,c in enumerate(clist):
    print(i,c)

0 a
1 f
2 go
3 tot


#### Operators
In the above we use the [augmented assignment](https://docs.python.org/2.0/ref/augassign.html) operator. It is an example of the many operators and constructs that are used to form [python expressions](https://docs.python.org/3/reference/expressions.html#). 

[Augmented assignments](https://docs.python.org/2.0/ref/augassign.html) are an example of how sometimes details do matter, as can be seen [when applying ]

#### Functions 
- `def` 
- function arguments: mandatory and optional
- lambda functions: 

In [93]:
def g(x,a=1):
    '''Calculate a*x^2
    
    Parameters
    ----------
    x : float
    input
    
    a : float
    input
    
    Returns
    -------
    g : float
    result
    '''
    g = a*x**2
    return g
g(3,a=2)

18

In [94]:
g?

Signature: g(x, a=1)
Docstring:
Calculate a*x^2

Parameters
----------
x : float
input

a : float
input

Returns
-------
g : float
result
File:      ~/mp248-course-notes/<ipython-input-93-12bf0cbcaed9>
Type:      function


In [90]:
a = 2.
f = lambda x: a*x**2
f(2)

8.0

#### Help and documentation
* getting help: `help(function)` or `function?`
* comments and documentation: doc strings

In [96]:
#sqrt?

In [98]:
#help(sqrt)

#### Example of using library
* random numbers: search for _numpy random_

In [100]:
#random?

In [101]:
random.random(5)

array([0.91926945, 0.82721529, 0.93409896, 0.31081609, 0.1135026 ])